### ISSUE TITLE
open current branch's upstream

### ISSUE THREAD

**Issue by lengyijun** [oren0e/gitopen#13]
```
git branch -vv
  add-appimage     ae682aa72a8b Add a CI job for packaging fish as an AppImage
* lyj-add-appimage 0a1cd4461ce7 [lyj/lyj-add-appimage] don't show ^C
  master           79f8364bc70a [origin/master] docs/completions: Add a teensy bit more
```

```
 cat .git/config 
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git@github.com:fish-shell/fish-shell.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[user]
        email = sjtu5140809011@gmail.com
        name = lengyijun
[remote "appimage"]
        url = git@github.com:mliszcz/fish-shell.git
        fetch = +refs/heads/*:refs/remotes/appimage/*
[branch "appimage"]
        remote = appimage 
        merge = refs/heads/add-appimage
[remote "lyj"]
        url = git@github.com:lengyijun/fish-shell.git
        fetch = +refs/heads/*:refs/remotes/lyj/*
[branch "lyj-add-appimage"]
        remote = lyj
        merge = refs/heads/lyj-add-appimage
```

```
git checkout master
gitopen # I want to open https://github.com/fish-shell/fish-shell/

git checkout  lyj-add-appimage
gitopen # I want to open https://github.com/lengyijun/fish-shell
```

**Comment by oren0e** [comment]
Hi, thanks for taking the time to improve this tool.
Can you please elaborate on what you mean by "upstream"? For example, say you branched out from `master` to `branchX` - you want a way to open the branched-from branch? (`master` in this case)

**Comment by lengyijun** [comment]
@oren0e updated in description

**Comment by oren0e** [comment]
From my understanding you want to open the original repo in the case you've forked it, and in case not - just the cloned-from repo. Am I correct?
If this is so, it's more complicated than I initially thought because "forking" is not a git concept (it's a platform concept e.g. github, gitlab, etc.). The safest bet then becomes to parse the git config file rather than relying on git commands to extract the needed information. I need to think about whether I want to deal with parsing configs or not since that incurs an overhead and `gitopen` should be first of all - fast.

**Comment by oren0e** [comment]
Closing the issue for now, if this is really needed there has to be a discussion about this feature first. Feel free to open this again if there's something to add to this.

**Comment by oren0e** [comment]
See related PR https://github.com/oren0e/gitopen/pull/16
